server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always

spring:
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml


  datasource:
    url: jdbc:postgresql://localhost:5432/region_dictionary_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver