server:
  port: 7777
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/region_dictionary_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    accessTokenHeader: "access_token"
    refreshTokenHeader: "refresh_token"
    accessTokenTimeout: 1
    refreshTokenTimeout: 10